project_id = "zauckuymszvczjulvhsw"

[functions.send-sms-verification]
verify_jwt = false

[functions.music-search]
verify_jwt = false

[functions.translate-text]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.check-payment]
verify_jwt = false
